version: '3.1'

services:

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'access_control'
            MYSQL_USER: 'deko'
            MYSQL_PASSWORD: '123456'
            MYSQL_ROOT_PASSWORD: '123456'
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
         test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
         timeout: 20s
         retries: 10

    access:
        depends_on:
            - db
        image: access:latest
        ports:
            - 8080:8080
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/access_control
            SPRING_DATASOURCE_USERNAME: deko
            SPRING_DATASOURCE_PASSWORD: 123456
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 123456    
    nginx:
       image: nginx:latest
       volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certs:/etc/nginx/certs
       ports:
        - 8443:443
       depends_on:
        - phpmyadmin
        - access
volumes:
    db_data: {}